---
title: "N_back_Classification"
format: html
editor: visual
---

## Data Manipulation

The data set used in this study is retrieved from the website of [Tufts HCI Lab](https://tufts-hci-lab.github.io/code_and_datasets/fNIRS2MW.html).

In the wide form of the data set we have 6818 observations from each of 68 subjects. The observations are ordered according to each n-back condition (*0→1→2→3→1→2→3→0→2→3→0→1→3→0→1→2*). The order of the task is the same for all subjects.

The first 10 observations on all columns are given as:

```{r message=FALSE}
library(dplyr)
# install.packages("tidyverse")
library(tidyverse)
library(magrittr)
```

```{r}
wide_form <- read.csv("wide.form.csv")
wide_form %>%
  slice(1:10)
```

```{r}
wide_form %<>% 
  mutate(Subject=as.factor(Subject))
```

```{r}
wide_form %>%
  select(Subject, AB_I_O, AB_I_DO, CD_I_O, CD_I_DO) %>%
  group_by(Subject) %>%
  summarise(Mean_AB_O=mean(AB_I_O),
            Mean_AB_DO=mean(AB_I_DO),
            Mean_CD_O=mean(CD_I_O),
            Mean_CD_DO=mean(CD_I_DO)
            )
```

sdkls


